mysite/myapp/urls.py
# django
from django.urls import path

# my_project
from myapp.views import index, indexItem, add_item , update_item

app_name = "myapp"

urlpatterns = [
    path("", index , name="index"),  # -> http://127.0.0.1:8000/myapp/
    path("<int:my_id>/", indexItem, name="detail"),  # -> http://127.0.0.1:8000/myapp/2/
    path(
        "add_item/", add_item, name="detail"
    ),  # ->http://127.0.0.1:8000/myapp/add_item/
    path("update_item/<int:my_id>/", update_item, name="update_item"),
]

mysite/mysite/urls.py
# django
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # вход в дамин панель
    path("admin/", admin.site.urls),
    path("myapp/", include("myapp.urls", namespace="myapp")),
]

# добаляем к нашим основным url-путям пути к нами медиа файлам
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/myapp/models.py
# django
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.CharField(max_length=200)
    # upload_to указывает куда будем сохранять фотографии, которые добавили через админку, также нужно указывать MEDIA_ROOT
    image = models.ImageField(blank=True, upload_to="images")

    def __str__(self):
        return self.name

mysite/myapp/views.py
# django
from django.shortcuts import render
from django.http import HttpResponse

# my_project
from myapp.models import Product


# главная страница сайта со всеми главынми товарами
def index(request):
    items = Product.objects.all()
    context = {"items": items}
    return render(request=request, template_name="myapp/index.html", context=context)


# страница для обозначений одной записи товара на сайте
# id значение передаеться пользователем в url-адрессе  # -> http://127.0.0.1:8000/myapp/hello/id/
def indexItem(request, my_id):
    item = Product.objects.get(id=my_id)
    context = {"item": item}
    return render(request=request, template_name="myapp/detail.html", context=context)


# страница для добавление нового товара на сайт
def add_item(request):
    # если запрос к сайту POST как мы укзаали в html форме <form method="post">
    if request.method == "POST":
        # берем значение поля формы , где указали name="name"
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        # внутри FILES храниться картинка, которую пользователь прередал на сайте, ну и другие файлы
        # берем значение поля формы , где указали name="upload"
        image = request.FILES["upload"]

        # создаме ячейку с данными, но еще ее не сохраняем
        item = Product(name=name, price=price, description=description, image=image)
        # сохраняем новосозданую ячейку в базе данных
        item.save()

    return render(request, template_name="myapp/additem.html")


# представления для изменения уже существующий елементов(товаром) в базе данных
def update_item(request, my_id):
    
    item = Product.objects.get(id=my_id)
    
    if request.method == "POST":
        item.name = request.POST.get("name")
        item.price = request.POST.get("price")
        item.description = request.POST.get("description")
        item.image = request.FILES["upload"]
        item.save()

    context = {"item": item}

    return render(request, template_name="myapp/updateitem.html", context=context)

mysite/myapp/templates/myapp/additem.html
{% extends "myapp/base.html" %}
{% comment %} форма для добавление новых елементов(товаров) в базу данных {% endcomment %}
{% block content %}
<div class="ml-[200px]">
    <h1 class="text-2xl m-10 font-bold text-green-600"> Add New Item Below</h1>
    <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8 " method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="mb-4 ">
            <label class="block text-gray-700 text-md font-bold mb-2" for="name">Item Name</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Name..." name="name" id="name">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Item Price</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Price..." name="price" id="price">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Item Description</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Description..." name="description" id="description">
            <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
            <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Item" value="Add Item">Add Item</button>
        </div>
    </form>
</div>

{% endblock content %}

mysite/myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}" />
    <title>Document</title>
  </head>
  <body>
    
    {% include "myapp/navbar.html" %}
    
    {% block content %}
          
    {% endblock %}
  </body>
</html>

mysite/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% load humanize %}

{% block content %}
  <div class="flex p-10 w-full h-200">
    <img class="w-1/3" src="{{ item.image.url }}" alt="itemPhoto" />
    <div class="w-2/3 text-xl ml-10 mt-7">
      <p class="mt-5">{{ item.name }}</p>
      <p class="mt-5 text-green-500">$ {{ item.price|intcomma }}</p>
      <p class="mt-5 text-gray-600">{{ item.description }}</p>
    </div>
  </div>
{% endblock %}

mysite/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block content %}
  <main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
    <div class="sm:text-center lg:text-left">
      <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
        <span class="block xl:inline">Ексклюзивные Товары</span>
        <span class="block xl:inline text-green-500">По Супер Ценам</span>
      </h1>
      <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lh sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Вы можете заказать товар из любой точки мира. Доставка Включена</p>
    </div>

    <div class="p-10 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-4 gap-4">
      {% for item in items %}
        <a href="{% url 'myapp:detail' item.id %}">
          <div class="rounded overflow-hidden shadow-lg transition-transform transform hover:scale-105">
            <img class="w-full h-[400px]" src="{{ item.image.url }}" alt="" />
            <div class="px-6 py-4">
              <p class="font-bold text-xl mb-2">{{ item.name }}</p>
              <p class="font-bold text-xl text-green-500 mb-2">${{ item.price }}</p>
              <p class="text-gray-700 text-base">{{ item.description }}</p>
            </div>
          </div>
        </a>
      {% endfor %}
    </div>
  </main>
{% endblock %}

mysite/myapp/templates/myapp/navbar.html
{% load static %}

<nav class="bg-white shadow-lg">
  <div class="max-w-6xl mx-auto px-4">
    <div class="flex justify-between">
      <div class="flex space-x-7">
        <div>
          <a href="{% url 'myapp:index' %}" class="flex items-center px-2 py-4">
            <img class="h-8 w-8" src="{% static 'myapp/images/shop.png' %} " alt="logo" />
            <span class="text-gray-500 font-semibold text-xl"  >Kondrich-Shop</span>
          </a>
        </div>
        <div class="items-center flex space-x-1">
          <a href="#" class="bg:py-4 px-2 text-gray-500 font-semibold border-b-4 border-green-500">Home</a>
          <a href="#" class="py-4 px-2 text-gray-500 font-semibold">About</a>
          <a href="#" class="py-4 px-2 text-gray-500 font-semibold">Contacts</a>
          <a href="#" class="py-4 px-2 text-gray-500 font-semibold">Place</a>
        </div>
      </div>
    </div>
  </div>
</nav>

mysite/myapp/templates/myapp/updateitem.html
{% extends 'myapp/base.html' %}
{% comment %}форма для изменения уже существующий елементов(товаров) в базе данных{% endcomment %}
{% block content %}
  <div class="ml-[200px]">
    <h1 class="text-2xl m-10 font-bold text-green-600">Update New Item</h1>
    <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="mb-4">
        <label class="block text-gray-700 text-md font-bold mb-2" for="name">Item Name</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{ item.name }}" type="text" placeholder="Name..." name="name" id="name" />
        <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Item Price</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{ item.price }}" type="text" placeholder="Price..." name="price" id="price" />
        <label class="block text-gray-700 text-md font-bold mb-2 mt-2">Item Description</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" for="description" value="{{ item.description }}" type="text" placeholder="Description..." name="description" id="description" />
        <img class="w-20 h-20" src="{{ item.image.url }}" alt="" />
        <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload" />
        <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Item" value="Add Item">Update Item</button>
      </div>
    </form>
  </div>
{% endblock %}